config/routes.rb
Rails.application.routes.draw do
  
  root 'api/companies#index'

	get 'api/backup', to: 'application#backup'

	namespace :api do
		resources :steps
		resources :companies
		resources :jobs
		resources :contacts
		resources :users
		resources :tasks
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :contacts
  has_many :jobs
  has_many :tasks
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :company
  has_many :tasks

  def name
    "#{self.fname}" + " " + "#{self.lname}"
  end
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :tasks
  belongs_to :company
  has_many :contacts, through: :company

	def self.job
		file = Nokogiri::HTML("https://www.simplyhired.com/search?q=react&l=boston%2C+ma&job=plwbKJoaUgzlToK_I5oTnGONK_95DjAhRjUc-X5B9mX5R9nKng05gg")  
		page = HTTParty.get(file)
		parse = Nokogiri::HTML(page) 
		urls= []
		parse.css('a').each do |a| 
			binding.pry
			a.css('.card')
			 
			# a.card-link

		end
	end


 end
 

app/models/step.rb
class Step < ApplicationRecord
  has_many :tasks

  def tech_prep
    # study
    # code
    # blog
  end

  def branding    # (user.tasks.build to complete each of these fields in Users table)
    # task_elevator_pitch
    # task_resume?
    # task_twitter_url?
    # task_linkedin_url?
    # task_github_url?
    # task_learn_student_profile_url?
    # task_blog_site_url?
    # task_portfolio_site_url?
    # task_github_API_track_commits
  end

  def job_search(student)
    # research
    # network
  end

  def job_apply
    # job_instructions_task_steps_created?
    # job_instructions_tasks_completed?
    # job_org_contact_info_entered?
  end

  def job_interview
    # meet
    # interview
    # fup
  end

  def job_offer
    # job_analyze(job_data)
  end

  def job_analyze
    # profile rank (see lib/notes/notes-feature-job-fit-module.md)
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user  
  belongs_to :contact
  belongs_to :job
  belongs_to :company
  belongs_to :step
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  has_many :jobs, through: :tasks
  has_many :contacts, through: :tasks
  has_many :companies, through: :tasks
  has_many :steps, through: :tasks

  validates :email, presence: true, uniqueness: true
 
end

app/controllers/api/companies_controller.rb
class Api::CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :update, :destroy]
  
  def index
    @companies = Company.all.order(:name)
    render json: @companies
  end
	
  def show
		render json: @company
  end
	
	def create
    @company = Company.new(company_params)
    if @company.save
			render json: @company
    else
			render json: { errors: { message: 'Company NOT created' }}
    end
  end
	
  def update
    @company.update(company_params)
    if @company.save
			render json: @company
    else
			render json: { errors: { message: 'Company NOT updated' }}
    end
  end

  def destroy
    @company.destroy
		render json: { message: 'Company deleted.' }
  end

  private
  def set_company
    @company = Company.find_by_id(params[:id])
  end

  def company_params
    params.require(:company).permit(:name, :city, :state, :url, :about)
  end
end

app/controllers/api/contacts_controller.rb
class Api::ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :update, :destroy]
  
  def index
    @contacts = Contact.all
    render json: @contacts
  end
	
  def show
		render json: @contact
  end

	def create
		
binding.pry

    @contact = Contact.new(contact_params)
    if @contact.save
      render json: @contact
    else
			render json: { errors: { message: 'Contact NOT created' }}
    end
  end
	
  def update
    @contact.update(contact_params)
		if @contact.save
			render json: @contact
    else
			render json: { errors: { message: 'Contact NOT updated' }}
    end
  end

  def destroy
    @contact.destroy
		render json: { message: 'Contact deleted.' }
  end

  private
  def set_contact
    @contact = Contact.find_by_id(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:fname, :lname, :title, :email, :phone, :url, :about, :linkedin, :twitter, :company_id)
  end
end

app/controllers/api/jobs_controller.rb
class Api::JobsController < ApplicationController
	before_action :set_job, only: [:show, :update, :destroy]
	
	def index 
		# @jobs = Job.all.order(:id)
		@jobs = Job.all
		render json: @jobs
	end

	def show
		render json: @job
	end
 
	def create
		@job = Job.new(job_params)
		if @job.save
			render json: @job
		else
			render json: { message: "Job NOT created."}
		end
	end

	def update
		@job.update(job_params)
		if @job.save
			render json: @job
		else
			render json: { message: 'Job NOT updated.'}
		end
	end

	def destroy
		@job.destroy
		render json: { message: 'Job deleted.'}
	end

	private
	def set_job
		@job = Job.find_by_id(params[:id])
	end

	def job_params
		params.require(:job).permit(:title, :url, :company_id, :description, :requirements, :instructions)
	end
end

app/controllers/api/steps_controller.rb
class Api::StepsController < ApplicationController
  before_action :set_step, only: [:show, :update, :destroy]
  
  def index
    @steps = Step.all
    render json: @steps
  end

	def show
		render json: @step
  end
 
  def create
    @step = Step.new(step_params)
    if @step.save
      render json: @step
    else
      render json: { message: "Step NOT created."}
    end
  end

  def update
    @step.update(step_params)
    if @step.save
      render json: @step
    else
      render json: { message: 'Step NOT updated.'}
    end
  end

  def destroy
    @step.destroy
    render json: { message: 'Step deleted.'}
  end

  private
  def set_step
    @step = Step.find_by_id(params[:id])
  end

  def step_params
    params.require(:step).permit(:name, :category)
  end
end

app/controllers/api/tasks_controller.rb
class Api::TasksController < ApplicationController
  before_action :set_task, only: [:show, :update, :destroy]
  
	def index
    @tasks = Task.all
    render json: @tasks
  end
   
	def show
		render json: @task
  end
 
	def create
		@task = Task.new(task_params)
    if @task.save
      render json: @task
    else
      render json: { message: 'Task NOT created.'}
    end
  end
	
  def edit
  end
	
  def update
    @task.update(task_params)
    if @task.save
      render json: @task
    else
      render json: { message: 'Task NOT updated.'}
    end
  end
	
  def destroy
  	@task.delete
    render json: { message: 'Task deleted.'}
  end
	
  private
  def set_task
    @task = Task.find_by_id(params[:id])
  end
	
	def task_params
		params.require(:task).permit(:user_id, :step_id, :job_id, :contact_id, :company_id, :due_date, :title, :priority, :notes)
   end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
	before_action :set_user, only: [:show, :update, :destroy]
 
  def index
		@users = User.all
		render json: @users
  end

  def show
    @user = User.find_by_id(params[:id])
    @task = @user.tasks.build
		render json: @user
  end

  def create
    @user = User.create(user_params)
    if @user.save
      render json: @user
    else
      render json: {message: 'User NOT created.'}
    end
  end

  def update
    @user.update_without_password(user_params)
    if @user.save
      render json: @user
    else
      render Json: { message: "User NOT updated"}
    end
  end

  def destroy
    @user.delete
		render json: { message: "User deleted."}
  end

  private
  def set_user
		@user = User.find_by_id(params[:id])
	end

  def user_params
		params.require(:user).permit(:name, :email, :password, :phone1, :phone2, :address_line1, :address_line2, :city, :state, :zip, :elevator_pitch, :resume, :twitter_url, :linkedin_url, :github_url, :learn_student_profile_url, :blog_site_url, :portfolio_site_url, :coach_name, :coach_email, :coach_slack)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API

	def backup
		exec 'rake db:data:dump && rake restart'
	end
end

app/views/layouts/_navbar_new.html.erb
<div class="nav-bar">
<% if current_user && user_signed_in? %>
  <button><%= link_to "new_company", new_company_path %></button>
  <button><%= link_to "new_contact", new_contact_path %></button>
  <button><%= link_to "new_job", new_job_path %></button>
  <button><%= link_to "new_task", new_user_task_path(current_user) %></button><br>
Welcome: <%= current_user.email.upcase %>
<% end %> Current DateTime: <%= Time.new.strftime("%Y-%m-%d %H:%M:%S") %>
</div>

app/views/layouts/_navbar_user.html.erb
<div class="nav-bar">
<% if !current_user %>
<button><%= link_to "home", home_path %></button>
<button><%= link_to "sign Up", new_user_registration_path %></button>
<button><%= link_to "sign In",  new_user_session_path %></button><br>
<% end %>

<% if current_user && user_signed_in? %>
  <button><%= link_to "home", root_path %></button>
  <button><%= link_to "sign out", destroy_user_session_path %></button>
  <button><%= link_to "account", user_path(current_user) %></button>
  <button><%= link_to "companies", companies_path %></button>
  <button><%= link_to "contacts", contacts_path %></button>
  <button><%= link_to "jobs", jobs_path %></button>
  <button><%= link_to "tasks", user_tasks_path(current_user) %></button>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>job-crm-v1</title>
    
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap-theme.min.css">
 
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'custom' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'users' %>
    <%= yield :js %>
 
  </head>
  <body>
    <div style="margin: 2%">
      <div class="nav-bar">
        <%= render partial: 'layouts/navbar_user' %>
        <%= render partial: 'layouts/navbar_new' %>
      </div>
      <div class="flash-style">
        <p><%= notice %><%= alert %></p>
      </div>
      <div class="row-fluid">
        <%= yield %>
      </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
  </body>
</html>